### ISSUE TITLE
Tray commands unreadable

### ISSUE THREAD

**Issue by smaragdus** [r57zone/Snapshots-for-Windows#1]
When this option is enabled:

`Minimize application to notification area (tray)`

**screen:**

![Snapshots 1 3 1 - 2021-06-21 - 007](https://user-images.githubusercontent.com/9025757/122694172-32b17880-d245-11eb-8022-b70a16492b30.png)

the tray commands are unreadable, showing question marks,

**screens:**

![Snapshots 1 3 1 - 2021-06-21 - 005](https://user-images.githubusercontent.com/9025757/122694218-5f659000-d245-11eb-8ada-294937428ef8.png)

![Snapshots 1 3 1 - 2021-06-21 - 006](https://user-images.githubusercontent.com/9025757/122694252-760be700-d245-11eb-8fb1-869b20be42c8.png)

I suppose that these commands should mean **Settings** and **Exit**:

- **????????? = Settings**
- **????? = Exit**

I am using [Snapshots](https://github.com/r57zone/Snapshots-for-Windows) [version](https://github.com/r57zone/Snapshots-for-Windows/releases) [1.3.1](https://github.com/r57zone/Snapshots-for-Windows/releases/tag/1.3.1) (the latest version). This happens on Windows 8 x64.

**Comment by r57zone** [comment]
Fixed, thanks
https://github.com/r57zone/Snapshots-for-Windows/releases

**Comment by smaragdus** [comment]
@r57zone 

Thank you for the extremely quick fix. I have just tested version [1.3.2](https://github.com/r57zone/Snapshots-for-Windows/releases/tag/1.3.2) and the tray commands appear just right, screen:

![Snapshots 1 3 2 - 2021-06-22 - 002](https://user-images.githubusercontent.com/9025757/122844663-cf8a1980-d30a-11eb-85f2-75859a03eaaf.png)

Off-topic- your [Snapshots](https://github.com/r57zone/Snapshots-for-Windows) tool is exactly to my liking- tiny, light, portable, plus I like programs written in Delphi/Pascal, which are usually smaller and lighter than those, written in C/C++, actually I think that only programs written in Assembler can be even smaller and lighter.  Because I like [Snapshots](https://sourceforge.net/projects/snapshots-win/) very much when I have time I may some suggest tiny improvements for future releases of the program.

Thanks for the nice program!
